- name: Install NGINX
  hosts: servers
  become: yes 
  tasks:
    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable NGINX service
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started

- name: Configure NGINX Virtual Host
  hosts: servers
  become: yes
  tasks:
    - name: Create directory for virtual host
      ansible.builtin.file:
        path: /var/www/{{ ansible_host }}/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create an index.html for the virtual host
      ansible.builtin.copy:
        dest: /var/www/{{ ansible_host }}/html/index.html
        content: "<html><h1>Hello from {{ ansible_host }}</h1></html>"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Create NGINX virtual host configuration file
      ansible.builtin.template:
        src: virtualhost.j2
        dest: /etc/nginx/sites-available/{{ ansible_host }}
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Enable virtual host by linking to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ ansible_host }}
        dest: /etc/nginx/sites-enabled/{{ ansible_host }}
        state: link

    - name: Remove default NGINX virtual host configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test NGINX configuration
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx

- name: Install Certbot with Nginx support
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-venv
          - libaugeas0
        state: present

    - name: Create a Python virtual environment for Certbot
      command: python3 -m venv /opt/certbot/
      args:
        creates: /opt/certbot/bin/pip

    - name: Upgrade pip in the virtual environment
      command: /opt/certbot/bin/pip install --upgrade pip

    - name: Install Certbot and Nginx plugin
      command: /opt/certbot/bin/pip install certbot certbot-nginx

    - name: Create a symlink for Certbot
      file:
        src: /opt/certbot/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: Obtain SSL certificates using Certbot
      command: certbot --nginx --non-interactive --agree-tos -m {{ notifications_email }} -d {{ ansible_host }}
